### ISSUE TITLE
Mixture model papers

### ISSUE THREAD

**Issue by cristobal-sifon** [pmelchior/astro-data-science#1]
Gaussian mixture model with uncertainties to identify red sequence galaxies: http://adsabs.harvard.edu/cgi-bin/bib_query?arXiv:0907.4383

**Comment by pmelchior** [comment]
This is fascinating! I didn't know this paper before. They write down the same log-likelihood as XD for heteroscedastic noise in a GMM (in 1D only, but still) at the same time as Bovy and company (eq. A6), but their Lagrangian Multiplier approach yields equations that are simply probability-weighted mean and covariance, with a correction term for the noise-induced extra covariance. Those in proper XD are a little more complicated because the true sample locations are never observed, so their means/covariances aren't meaningful. So, I think these guys here over-interpret the data in a quite subtle way.

So, we can include it, but we should add a caveat!

**Comment by cristobal-sifon** [comment]
I think this one fits in the "Mixture models in likelihoods" item: fitting linear relations with (correlated) uncertainties, intrinsic scatter and selection effects http://adsabs.harvard.edu/abs/2007ApJ...665.1489K
